import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="h-dvh w-full flex justify-center items-center bg-transparent p-2 overflow-hidden">
				{children}
			</body>
		</html>
	);
}
